apps/article/models.py
from datetime import datetime

from exts import db

class Article_type(db.Model):
    __tablename__ = 'type'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type_name = db.Column(db.String(20), nullable=False)
    articles = db.relationship('Article', backref='articletype')


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(50), nullable=False)
    content = db.Column(db.Text, nullable=False)
    pdatetime = db.Column(db.DateTime, default=datetime.now)
    click_num = db.Column(db.Integer, default=0)
    save_num = db.Column(db.Integer, default=0)
    love_num = db.Column(db.Integer, default=0)
    # 外键 同步到数据库的外键关系
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    type_id = db.Column(db.Integer, db.ForeignKey('type.id'), nullable=False)
    comments = db.relationship('Comment', backref='article')


class Comment(db.Model):
    # 自定义表的名字
    __tablename__ = 'comment'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    comment = db.Column(db.String(255), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
    cdatetime = db.Column(db.DateTime, default=datetime.now)

    def __str__(self):
        return self.comment

apps/article/views.py
from flask import Blueprint, request, g, redirect, url_for, \
    render_template, jsonify, session

from apps.article.models import Article, Article_type, Comment
from apps.user.models import User
from exts import db

article_bp1 = Blueprint('article', __name__, url_prefix='/article')


# 自定义过滤器
@article_bp1.app_template_filter('cdecode')
def content_decode(content):
    content = content.decode('utf-8')
    return content

@article_bp1.route('/publish/', methods=['POST', 'GET'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        type_id = request.form.get('type')
        content = request.form.get('content')
        # 添加文章
        article = Article()
        article.title = title
        article.type_id = type_id
        article.content = content
        article.user_id = g.user.id
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('user.index'))


@article_bp1.route('/detail/',methods=["POST","GET"])
def article_detail():
    # 获取文章对象通过id
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    # 获取文章分类
    types = Article_type.query.all()
    user_id = session.get('uid')
    user = None
    if user_id:
        user = User.query.get(user_id)
    page = int(request.args.get('page', 1))
    comments = Comment.query.filter(Comment.article_id == article_id).order_by(-Comment.cdatetime).paginate(page=page , per_page=3)

    return render_template('article/detail3.html', article=article, types=types,user=user,comments=comments)


@article_bp1.route('/love/')
def article_love():
    article_id = request.args.get('aid')
    tag = request.args.get('tag')

    article = Article.query.get(article_id)
    if tag == '1':
        article.love_num -= 1
    else:
        article.love_num += 1
    db.session.commit()
    return jsonify(num=article.love_num)

#发表文章的评论
@article_bp1.route("/article_comment/",methods=["POST","GET"],endpoint="comment")
def article_detail():
    if request.method == "POST":
        comment_content = request.form.get('comment')
        user_id = g.user.id
        article_id = request.form.get("aid")
        comment = Comment()
        comment.comment = comment_content
        comment.user_id = user_id
        comment.article_id = article_id
        try:
            db.session.add(comment)
            db.session.commit()
            return redirect(url_for('article.article_detail')+f"?aid={article_id}")
        except Exception as e:
            print(f"出现错误啦{e}")
            db.session.rollback()
            return
    return redirect(url_for('user.index'))

@article_bp1.route('/type_search/')
def type_search():
    uid = session.get("uid")
    user = None
    if uid:
        user = User.query.get(uid)
    types = Article_type.query.all()
    type_id = request.args.get('tid')
    type = Article_type.query.get(type_id)
    return render_template('article/article_type.html',user=user,types=types,type=type)

templates/article/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加文章</title>
</head>
<body>
<form action="{{ url_for('article.publish_article') }}" method="post">
    <p><input type="text" name="title" placeholder="文章标题"></p>
    <p>
        <textarea cols="50" rows="10" placeholder="输入文章内容(暂时不要输入表情)" name="content">

        </textarea>
    </p>
    <p>
        用户：
        <select name="uid">
            <option value="0">请选择用户</option>
            {% for user in users %}
                <option value="{{ user.id }}"> {{ user.username }}</option>
            {% endfor %}
        </select>
    </p>
    <p><input type="submit" value="添加文章"></p>
</form>

</body>
</html>

templates/article/article_type.html
{% extends 'base.html' %}
{% block title %}
    文章分类
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }

        .article {
            width: 90%;
            margin: 20px auto;
            padding: 5px 10px;
            background-color: rgba(131, 202, 227, 0.7);
            border-bottom: 1px solid gray;
        }

        .article p {
            font-size: 14px;
        rgba(75, 75, 74, 1.00);
        }

        .article h4 a {
            color: rgba(80, 80, 79, 1.00);
        }

        .article h4 a:hover {
            color: black;
        }

        .article div span {
            margin-left: 20px;
        }

        .article div {
            margin-bottom: 18px;
        }

    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        {% for article in type.articles %}
            <div class="article">
                <h4><a href="{{ url_for('article.article_detail') }}?aid={{ article.id }}">{{ article.title }}</a></h4>
                <p>
                    <span>作者：{{ article.user.username }}</span>
                    <br>
                    <br>
                <div>{{ article.content | cdecode | safe }}</div>
                </p>
                <div>
                    <span style="margin-left: 0">发布时间：{{ article.pdatetime }}</span>
                    <span>收藏:{{ article.save_num }}</span><span>点击量:{{ article.click_num }}</span><span>点赞量:{{ article.love_num }}</span>
                </div>
            </div>
        {% endfor %}

        <nav aria-label="Page navigation" class="col-md-offset-5">
            <ul class="pagination">

            </ul>
        </nav>
    </div>
{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }
        #detail{
            background-color: rgba(232, 243, 242, 0.5);
            width: 90%;
            margin-top: 50px;
        }
        #detail h2{
            text-align: center;
        }
        #detail p {
            overflow: auto;
        }

        #left {
            float: left;
        }

        #right {
            float: right;
            margin-right: 30px;
        }

        #content {
            margin-top: 30px;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <p>
            <div id="left">作者:{{ article.user.username }} &nbsp;&nbsp;&nbsp; &nbsp;
                发布时间: {{ article.pdatetime }}</div>
            <div id="right">
                <span class="glyphicon glyphicon-heart"
                      aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.save_num }}</span>
                &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
                <span class="glyphicon glyphicon-thumbs-up"
                      aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.love_num }}</span>
            </div>
            </p>
            <div id="content">
                {{ article.content | safe }}
            </div>


        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 收藏
            $('.glyphicon-heart').click(function () {

            });
            // 点赞
            $('.glyphicon-thumbs-up').click(function () {

                let $this = $(this);
                let tag = $this.next('span').attr('tag');

                $.get('{{ url_for('article.article_love') }}', {aid:{{article.id}},tag:tag}, function (data) {
                    $this.next('span').text(data.num);

                });
                if (tag == 1) {
                    $this.css({'color':'black'});
                    $this.next('span').attr('tag',"0");
                } else {
                    $this.css({'color':'red'});
                    $this.next('span').attr('tag',"1");
                }


            });

        })
    </script>
{% endblock %}

templates/article/detail3.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }

        #detail {
            background-color: rgba(232, 243, 242, 0.6);
            border-radius: 10px;
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 20px 50px;
        }

        #detail h2 {
            text-align: center;
        }

        #detail h2 + div {
            height: 30px;
            line-height: 30px;
        }

        #left {
            float: left;
        }

        #right {
            float: right;
            margin-right: 30px;
        }

        #content {
            margin-top: 30px;
        }

        .item {
            overflow: auto;
            border-bottom: 1px solid lightgray;
            margin-bottom: 20px;
            padding: 10px;
        }

        #item_left {
            float: left;
            width: 10%;
            text-align: center;
        }

        #item_left img {
            width: 50px;
            height: 50px;
            border-radius: 25px;
        }

        #item_right {
            float: right;
            width: 90%;
        }

    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <div>
                <div id="left">作者:{{ article.user.username }} &nbsp;&nbsp;&nbsp; &nbsp;
                    发布时间: {{ article.pdatetime }}</div>
                <div id="right">
                    <span class="glyphicon glyphicon-heart"
                          aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.save_num }}</span>
                    &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
                    <span class="glyphicon glyphicon-thumbs-up"
                          aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.love_num }}</span>
                </div>
            </div>
            <div id="content">
                {{ article.content| cdecode |safe }}
            </div>
            <hr>
            <div id="comment">
                <p>文章评论:</p>
                <div>
                    <form action="{{ url_for('article.comment') }}" method="post">
                        <input type="hidden" name="aid" value="{{ article.id }}">
                        <p>
                    <textarea name="comment" class="form-control" style="width: 60%" rows="5" cols="60">写下你想说的，开始我们的对话
                    </textarea>
                        </p>
                        <p><input type="submit" value="评论" class="btn btn-info"></p>
                    </form>
                </div>
                <p style="margin: 20px 5px; border-bottom: 1px solid lightgray">

                </p>
                <div id="comment_item">
                    {% if comments.items %}
                    {% for comment in comments.items %}
                            <div class="item">
                                <div id="item_left">
                                    <img src=" {% if comment.user.icon %} {{ url_for('static',filename=comment.user.icon) }} {% else %}
                                    {{ url_for('static',filename='images/touxiang.jpg') }}{% endif %}"
                                         alt="">
                                </div>
                                <div id="item_right">
                                    <p>
                                        <span>{{ comment.user.username }}</span>
                                        <span>{{ comment.cdatetime }}</span>
                                    </p>
                                    <p>
                                        {{ comment.comment }}
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                        {% else %}
                         <div class="item">
                         当前文章还没有任何评论，快点发表评论吧
                         </div>
                        {% endif %}
                </div>
                <div id="paginate">
                    <nav aria-label="...">
                        <ul class="pager">
                            <li class="previous {% if not comments.has_prev %}disabled{% endif %}"><a
                                    href="{{ url_for('article.article_detail') }}?page={{ comments.prev_num }}&aid={{ article.id }}"><span
                                    aria-hidden="true">&larr;</span> 上一页</a></li>

                            <li class="next {% if not comments.has_next %}disabled {% endif %}"><a
                                    href="{{ url_for('article.article_detail') }}?page={{ comments.next_num }}&aid={{ article.id }}">下一页
                                <span
                                        aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>

                </div>
            </div>

        </div>

    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 收藏
            $('.glyphicon-heart').click(function () {

            });
            // 点赞
            $('.glyphicon-thumbs-up').click(function () {

                let $this = $(this);
                let tag = $this.next('span').attr('tag');

                $.get('{{ url_for('article.article_love') }}', {aid:{{article.id}}, tag: tag}, function (data) {
                    $this.next('span').text(data.num);

                });
                if (tag == 1) {
                    $this.css({'color': 'black'});
                    $this.next('span').attr('tag', "0");
                } else {
                    $this.css({'color': 'red'});
                    $this.next('span').attr('tag', "1");
                }


            });
            //文本域
            $('textarea[name="comment"]').focus(function () {
                $(this).val("")
            })

        })
    </script>
{% endblock %}