apps/user/models.py
from datetime import datetime

from exts import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(15), nullable=False)
    password = db.Column(db.String(256), nullable=False)
    phone = db.Column(db.String(11), unique=True, nullable=False)
    email = db.Column(db.String(30))
    icon = db.Column(db.String(100))
    isdelete = db.Column(db.Boolean, default=False)
    rdatetime = db.Column(db.DateTime, default=datetime.now)
    # 增加一个字段
    articles = db.relationship('Article', backref='user')
    comments = db.relationship("Comment",backref='user')

    def __str__(self):
        return self.username

class  Photo(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    photo_name = db.Column(db.String(50),nullable=False)
    photo_datatime = db.Column(db.DateTime,default=datetime.now)
    user_id = db.Column(db.Integer,db.ForeignKey("user.id"),nullable=False)

    def  __str__(self):
        return self.photo_name

class Aboutme(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    content = db.Column(db.Text,nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'))
    user = db.relationship("User",backref="aboutme")

class Messageboard(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    content = db.Column(db.String(500),nullable=False)
    mdatetime = db.Column(db.DateTime,default=datetime.now)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'))
    user = db.relationship("User",backref="messages")

apps/article/views.py
from flask import Blueprint, request, g, redirect, url_for, \
    render_template, jsonify, session

from apps.article.models import Article, Article_type, Comment
from apps.user.models import User
from exts import db

article_bp1 = Blueprint('article', __name__, url_prefix='/article')


# 自定义过滤器
@article_bp1.app_template_filter('cdecode')
def content_decode(content):
    content = content.decode('utf-8')
    return content

@article_bp1.route('/publish/', methods=['POST', 'GET'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        type_id = request.form.get('type')
        content = request.form.get('content')
        # 添加文章
        article = Article()
        article.title = title
        article.type_id = type_id
        article.content = content
        article.user_id = g.user.id
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('user.index'))


@article_bp1.route('/detail/',methods=["POST","GET"])
def article_detail():
    # 获取文章对象通过id
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    # 获取文章分类
    types = Article_type.query.all()
    user_id = session.get('uid')
    user = None
    if user_id:
        user = User.query.get(user_id)
    page = int(request.args.get('page', 1))
    comments = Comment.query.filter(Comment.article_id == article_id).order_by(-Comment.cdatetime).paginate(page=page , per_page=3)

    return render_template('article/detail3.html', article=article, types=types,user=user,comments=comments)


@article_bp1.route('/love/')
def article_love():
    article_id = request.args.get('aid')
    tag = request.args.get('tag')

    article = Article.query.get(article_id)
    if tag == '1':
        article.love_num -= 1
    else:
        article.love_num += 1
    db.session.commit()
    return jsonify(num=article.love_num)

#发表文章的评论
@article_bp1.route("/article_comment/",methods=["POST","GET"],endpoint="comment")
def article_detail():
    if request.method == "POST":
        comment_content = request.form.get('comment')
        user_id = g.user.id
        article_id = request.form.get("aid")
        comment = Comment()
        comment.comment = comment_content
        comment.user_id = user_id
        comment.article_id = article_id
        try:
            db.session.add(comment)
            db.session.commit()
            return redirect(url_for('article.article_detail')+f"?aid={article_id}")
        except Exception as e:
            print(f"出现错误啦{e}")
            db.session.rollback()
            return
    return redirect(url_for('user.index'))

@article_bp1.route('/type_search/')
def type_search():
    uid = session.get("uid")
    user = None
    if uid:
        user = User.query.get(uid)
    types = Article_type.query.all()
    type_id = request.args.get('tid')
    type = Article_type.query.get(type_id)
    return render_template('article/article_type.html',user=user,types=types,type=type)

apps/user/views.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename

from apps.article.models import Article_type, Article
from apps.user.models import User, Photo, Aboutme, Messageboard
from apps.utils.utils import upload_qiniu, delete_qiniu
from exts import db
from settings import Config

user_bp1 = Blueprint('user', __name__, url_prefix='/user')

required_login_list = ['/user/center/', '/user/change/',
                       '/article/publish/', "/user/upload_photo/"
                       , "/user/photo_del/",
                         "/article/article_comment/",
                        "/user/aboutme/",
                         "/user/show_about/"]



# ****重点*****
@user_bp1.before_app_request
def before_request1():
    if request.path in required_login_list:
        id = session.get('uid')
        if not id:
            return render_template('user/login.html')
        else:
            user = User.query.get(id)
            # g对象，本次请求的对象
            g.user = user


@user_bp1.app_template_filter('cdecode')
def content_decode(content):
    content = content.decode('utf-8')
    return content[:200]

@user_bp1.app_template_filter('cdecode1')
def content_decode(content):
    content = content.decode('utf-8')
    return content


# 首页
@user_bp1.route('/')
def index():
    uid = session.get('uid')

    page = int(request.args.get('page', 1))
    pagination = Article.query.order_by(-Article.pdatetime).paginate(page=page, per_page=5)
    # 获取分类列表
    types = Article_type.query.all()
    # 判断用户是否登录
    if uid:
        user = User.query.get(uid)
        return render_template('user/index.html', user=user, types=types, pagination=pagination)
    else:
        return render_template('user/index.html', types=types, pagination=pagination)


# 用户注册
@user_bp1.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')
        email = request.form.get('email')
        if password == repassword:
            # 注册用户
            user = User()
            user.username = username
            # 使用自带的函数实现加密：generate_password_hash
            user.password = generate_password_hash(password)
            # print(password)
            user.phone = phone
            user.email = email
            # 添加并提交
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.index'))
    return render_template('user/register.html')


# 手机号码验证
@user_bp1.route('/checkphone/', methods=['GET', 'POST'])
def check_phone():
    phone = request.args.get('phone')
    user = User.query.filter(User.phone == phone).all()
    print(user)
    # code: 400 不能用    200 可以用
    if len(user) > 0:
        return jsonify(code=400, msg='此号码已被注册')
    else:
        return jsonify(code=200, msg='此号码可用')


# 用户登录
@user_bp1.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        f = request.args.get('f')
        if f == '1':  # 用户名或者密码
            username = request.form.get('username')
            password = request.form.get('password')
            users = User.query.filter(User.username == username).all()
            for user in users:
                # 如果flag=True表示匹配，否则密码不匹配
                flag = check_password_hash(user.password, password)
                if flag:
                    # 1。cookie实现机制
                    # response = redirect(url_for('user.index'))
                    # response.set_cookie('uid', str(user.id), max_age=1800)
                    # return response
                    # 2。session机制,session当成字典使用
                    session['uid'] = user.id
                    return redirect(url_for('user.index'))
            else:
                return render_template('user/login.html', msg='用户名或者密码有误')
        elif f == '2':  # 手机号码与验证码
            print('----->22222')
            phone = request.form.get('phone')
            code = request.form.get('code')
            # 先验证验证码
            valid_code = session.get(phone)
            print('valid_code:' + str(valid_code))
            if code == valid_code:
                # 查询数据库
                user = User.query.filter(User.phone == phone).first()
                print(user)
                if user:
                    # 登录成功
                    session['uid'] = user.id
                    return redirect(url_for('user.index'))
                else:
                    return render_template('user/login.html', msg='此号码未注册')
            else:
                return render_template('user/login.html', msg='验证码有误！')

    return render_template('user/login.html')


# 发送短信息
@user_bp1.route('/sendMsg/')
def send_message():
    phone = request.form.get("phone")
    session[phone] = "5201314"
    return jsonify(code=200, msg="短信发送成功")

# 用户退出
@user_bp1.route('/logout/')
def logout():
    # 1。 cookie的方式
    # response = redirect(url_for('user.index'))
    # 通过response对象的delete_cookie(key),key就是要删除的cookie的key
    # response.delete_cookie('uid')
    # 2。session的方式
    # del session['uid']
    session.clear()
    return redirect(url_for('user.index'))


# 用户中心
@user_bp1.route('/center/')
def user_center():
    types = Article_type.query.all()
    photos = Photo.query.filter(Photo.user_id == g.user.id).all()
    return render_template('user/center.html', user=g.user, types=types,photos=photos)


# 图片的扩展名
ALLOWED_EXTENSIONS = ['jpg', 'png', 'gif', 'bmp',"jpeg"]


# 用户信息修改
@user_bp1.route('/change/', methods=['GET', 'POST'])
def user_change():
    if request.method == 'POST':
        username = request.form.get('username')
        phone = request.form.get('phone')
        email = request.form.get('email')
        # 只要有文件（图片），获取方式必须使用request.files.get(name)
        icon = request.files.get('icon')
        # print('======>', icon)  # FileStorage
        # 属性： filename 用户获取文件的名字
        # 方法:  save(保存路径)
        icon_name = icon.filename  # 1440w.jpg
        suffix = icon_name.rsplit('.')[-1]
        if suffix in ALLOWED_EXTENSIONS:
            icon_name = secure_filename(icon_name)  # 保证文件名是符合python的命名规则
            file_path = os.path.join(Config.UPLOAD_ICON_DIR, icon_name)
            icon.save(file_path)
            # 保存成功
            user = g.user
            user.username = username
            user.phone = phone
            user.email = email
            path = 'upload/icon/'
            user.icon = path + icon_name
            db.session.commit()
            return redirect(url_for('user.user_center'))
        else:
            return render_template('user/center.html', user=g.user, msg='必须是扩展名是：jpg,png,gif,bmp格式')

        # 查询一下手机号码
        # users = User.query.all()
        # for user in users:
        #     if user.phone == phone:
        #         # 说明数据库中已经有人注册此号码
        #         return render_template('user/center.html', user=g.user,msg='此号码已被注册')
        #

    return render_template('user/center.html', user=g.user)

@user_bp1.route("/upload_photo/",methods=["POST","GET"],endpoint="photo")
def upload_photo():
    if request.method == "POST":
        #获取对应的上传的内容
        photo = request.files.get('photo')
        #工具模块当中封装的一个模块
        ret,info = upload_qiniu(photo)
        if info.status_code == 200:
            photo = Photo()
            photo.photo_name = ret["key"]
            photo.user_id = g.user.id
            db.session.add(photo)
            db.session.commit()
            return "上传成功"
        else:
            return "上传失败！"

@user_bp1.route("/myphoto/")
def myphoto():
    page = int(request.args.get("page",1))
    photos = Photo.query.paginate(page=page,per_page=3)
    user_id = session.get("uid")
    user  = None
    if user_id:
        user = User.query.get(user_id)
        return render_template("user/myphoto.html",photos=photos,user=user)


@user_bp1.route("/photo_del/")
def photo_del():
    pid = request.args.get("pid")
    photo = Photo.query.get(pid)
    photo_name = photo.photo_name
    info = delete_qiniu(file_name=photo_name)
    if info.status_code == 200:
        #数据库进行删除
        db.session.delete(photo)
        db.session.commit()
        return redirect(url_for('user.user_center'))
    else:
        return render_template('user/500.html',err_msg='删除相册图片失败')


@user_bp1.route("/error/")
def error():
    referer = request.headers.get("Referer",None)
    return render_template('user/500.html',err_msg='有误',referer=referer)

@user_bp1.route('/aboutme/',methods=["POST","GET"])
def about_me():
    content = request.form.get("about_content")
    aboutme = Aboutme()
    aboutme.content = content
    aboutme.user_id = g.user.id
    try:
        db.session.add(aboutme)
        db.session.commit()
        return render_template('user/aboutme.html', user=g.user)
    except Exception as e:
        print(f"出现错误啦=====>{e}")
        db.session.rollback()
        return render_template("user/500.html",err_msg="数据库存储出现错误")


@user_bp1.route("/show_about/")
def show_about():
    return render_template("user/aboutme.html",user = g.user )


@user_bp1.route("/board/",methods=['POST',"GET"])
def show_board():
    uid = session.get("uid")
    user = None
    if uid:
        user = User.query.get(uid)
    page = int(request.args.get('page',1))
    boards = Messageboard.query.order_by(-Messageboard.mdatetime).paginate(page=page,per_page=3)
    if request.method == "POST":
        content = request.form.get('board')
        msg_board = Messageboard()
        msg_board.content = content
        if uid:
            msg_board.user_id = uid
            db.session.add(msg_board)
            db.session.commit()
            return redirect(url_for('user.show_board'))
    return render_template("user/board.html",user=user,boards=boards)

templates/user/center.html
{% extends 'base.html' %}
{% block title %}
    用户中心
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/center.css') }}">
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
            <p>管理相册</p>
            <p>管理留言</p>
            <p>关于我设置</p>
        </div>
        <div id="right">
            <div class="right1">
                <h2> 用户信息修改</h2>
                <form action="{{ url_for('user.user_change') }}" method="post" enctype="multipart/form-data">
                    <p><input type="text" class="form-control" id="InputUsername" name="username"
                              value="{{ g.user.username }}">
                    </p>
                    <p><input type="text" class="form-control" id="InputPhone" name="phone"
                              value="{{ g.user.phone }}"><span></span>
                    </p>
                    <p><input type="email" class="form-control" id="InputEmail1" name="email"
                              value="{{ g.user.email }}">
                    </p>
                    <p>点击选择文件修改头像</p>
                    <p><input type="file" id="exampleInputFile" name="icon" ></p>
                    <p>
                        <img src="{% if g.user.icon %} {{ url_for('static',filename=user.icon) }} {% else %}
                            {{ url_for('static',filename='images/touxiang.jpg') }}{% endif %}"
                             alt="" width="90"
                             height="100">
                    </p>
                    <p>
                        <button type="submit" class="btn btn-primary">用户信息修改</button>
                    </p>

                </form>
            </div>
            <div class="right1" style="padding-top: 20px">
                <form action="{{ url_for('article.publish_article') }}" method="post">
                    <p><input type="text" class="form-control" id="InputTitle" name="title"
                              placeholder="请输入文章标题">
                    </p>
                    <p>
                        <select name="type" class="form-control">
                            <option value="0">请选择文章分类</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.type_name }}</option>
                            {% endfor %}

                        </select>
                    </p>
                    <p>
                        <textarea name="content" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">发表文章</button>
                    </p>

                </form>
            </div>
            <div class="right1">
                <form action="{{ url_for('user.photo') }}" method="post" enctype="multipart/form-data"
                      class="form-inline">
                    <input type="file" name="photo" class="form-control">
                    <input type="submit" value="上传相册" class="btn btn-default">
                </form>
                <div class="row">
                    <div class="col-sm-12">
                        <h3>我的相册</h3>
                        <div class="row">
                            {% for photo in photos %}
                                <div class="col-xs-8 col-sm-4">
                                {# qy8vyhm5g.hn-bkt.clouddn.com #}
                                    <img src="http://qyan1rhti.hn-bkt.clouddn.com/{{ photo.photo_name }}"
                                         alt="..." class="img-rounded image">
                                    <button class="btn btn-info btn-xs photo-del" tag="{{ photo.id }}">删除</button>
                                </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
            <div class="right1" style="padding-top: 30px;width: 90%;">
                {% if user.messages %}
                <table class="table table-hover">
                    <tr>
                        <th>序号</th>
                        <th>留言</th>
                        <th>时间</th>
                        <th>操作</th>
                    </tr>
                    {% for message in user.messages %}
                        <tr {% if loop.index % 2 ==0  %} class="success" {% endif %}>
                            <td>{{ loop.index }}</td>
                            <td>{{ message.content }}</td>
                            <td>{{ message.mdatetime }}</td>
                            <td><a href="{{ url_for('user.delete_board') }}?bid={{ message.id }}">删除留言</a></td>
                        </tr>
                    {% endfor %}

                </table>
                    {% else %}
                    <p>还没有任何留言，可以去留言板进行留言</p>
                    {% endif %}

            </div>
            <div class="right1" style="padding-top: 30px">
                <form action="{{ url_for('user.about_me') }}" method="post" enctype="multipart/form-data">
                    <p>
                        <textarea name="about_content" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">更改我的</button>
                    </p>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/center.js') }}"></script>
{% endblock %}

templates/user/center2.html
{% extends 'base.html' %}
{% block title %}
    用户中心
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/center.css') }}">
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
            <p>管理相册</p>
            <p>管理留言</p>
            <p>关于我设置</p>
        </div>
        <div id="right">
            <div class="right1">
                <h2> 用户信息修改</h2>
                <form action="{{ url_for('user.user_change') }}" method="post" enctype="multipart/form-data">
                    <p><input type="text" class="form-control" id="InputUsername" name="username"
                              value="{{ g.user.username }}">
                    </p>
                    <p><input type="text" class="form-control" id="InputPhone" name="phone"
                              value="{{ g.user.phone }}"><span></span>
                    </p>
                    <p><input type="email" class="form-control" id="InputEmail1" name="email"
                              value="{{ g.user.email }}">
                    </p>
                    <p><input type="file" id="exampleInputFile" name="icon"></p>
                    <p>
                        <img src="{% if g.user.icon %} {{ url_for('static',filename=user.icon) }} {% else %}{{ url_for('static',filename='images/touxiang.jpg') }}{% endif %}"
                             alt="" width="90"
                             height="100">
                    </p>
                    <p>
                        <button type="submit" class="btn btn-primary">用户信息修改</button>
                    </p>

                </form>
            </div>
            <div class="right1" style="padding-top: 20px">
                <form action="{{ url_for('article.publish_article') }}" method="post">
                    <p><input type="text" class="form-control" id="InputTitle" name="title"
                              placeholder="请输入文章标题">
                    </p>
                    <p>
                        <select name="type" class="form-control">
                            <option value="0">请选择文章分类</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.type_name }}</option>
                            {% endfor %}

                        </select>
                    </p>
                    <p>
                        <textarea name="content" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">发表文章</button>
                    </p>

                </form>
            </div>
            <div class="right1">
                <form action="{{ url_for('user.upload_photo') }}" method="post" enctype="multipart/form-data"
                      class="form-inline">
                    <input type="file" name="photo" class="form-control">
                    <input type="submit" value="上传相册" class="btn btn-default">
                </form>
                <div class="row">
                    <div class="col-sm-12">
                        <h3>我的相册</h3>
                        <div class="row">
                            {% for photo in photos %}
                                <div class="col-xs-8 col-sm-4">
                                    <img src="http://qb894qzgn.bkt.clouddn.com/{{ photo.photo_name }}"
                                         alt="..." class="img-rounded image">
                                    <button class="btn btn-info btn-xs photo-del" tag="{{ photo.id }}">删除</button>
                                </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>

            </div>
            <div class="right1" style="padding-top: 30px;width: 90%">
                {% if user.messages %}
                    <table class="table table-hover">
                        <tr>
                            <th>序号</th>
                            <th>留言</th>
                            <th>时间</th>
                            <th>操作</th>
                        </tr>
                        {% for message in user.messages %}
                            <tr {% if loop.index%2==0 %}class="warning" {% endif %}>
                                <td>{{ loop.index }}</td>
                                <td>{{ message.content }}</td>
                                <td>{{ message.mdatetime }}</td>
                                <td><a href="{{ url_for('user.delete_board') }}?bid={{ message.id }}">删除留言</a></td>
                            </tr>
                        {% endfor %}


                    </table>
                {% else %}
                    <p>还没有任何内容，可以去留言板去发言...</p>
                {% endif %}
            </div>
            <div class="right1" style="padding-top: 30px">
                <form action="{{ url_for('user.about_me') }}" method="post" enctype="multipart/form-data">
                    <p>
                        <textarea name="about" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">更改我的</button>
                    </p>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/center.js') }}"></script>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block title %}
    用户注册
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
        }

        #container h1 {
            text-align: center;
            margin-bottom: 50px;
        }

        #container form {

            margin: 0 auto;
        }

        #tab {
            font-size: 20px;
            text-align: left;
            padding-left: 250px;
            margin-bottom: 20px;
        }

        #tab span {
            display: inline-block;
            padding: 10px;
            text-align: center;
            cursor: default;
            color: #f3f3f3;
        }

        .tips {
            color: red;
            font-size: 14px;
        }

        #btnCheck {
            width: 140px;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        <h1>用户登录</h1>
        <div id="tab">
            <span>用户名 / 密码</span> | <span>手机验证码</span>
        </div>
        <div class="logintab">
            <p class="tips">{{ msg }}</p>
            <form class="form-horizontal" method="post" action="{{ url_for('user.login') }}?f=1">
                <div class="form-group">

                    <div class="col-md-6 col-md-offset-3">
                        <input type="text" class="form-control" id="inputUsername" placeholder="username"
                               name="username">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <input type="password" class="form-control" id="inputPassword" placeholder="password"
                               name="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-10">
                        <button type="submit" class="btn btn-primary col-md-3">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录
                        </button>
                        <button type="reset" class="btn btn-primary col-md-3 col-md-offset-1">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="logintab">
            <p class="tips">{{ msg }}</p>
            <form class="form-horizontal" method="post" action="{{ url_for('user.login') }}?f=2">
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <input type="text" class="form-control" id="inputPhone" placeholder="输入手机号码"
                               name="phone"><span></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-3">
                        <input type="text" class="form-control" id="inputCode" placeholder="输入验证码"
                               name="code">
                    </div>
                    <div class="col-md-2">
                        <input type="button" id="btnCheck" class="btn btn-info" value="发送验证码"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-10">
                        <button type="submit" class="btn btn-primary col-md-3">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录
                        </button>
                        <button type="reset" class="btn btn-primary col-md-3 col-md-offset-1">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
                // 显示|隐藏 登录方式
                $(".logintab").hide();
                $(".logintab").first().show();
                $("#tab span").each(function (i) {
                    $(this).click(function () {
                        $(".logintab").hide();
                        $(".logintab").eq(i).show();
                    })
                });

                // 发送验证码
                $('#btnCheck').click(function () {
                    let phone = $('#inputPhone').val();
                    let span_obj = $('#inputPhone').next('span');
                    span_obj.css({'color': 'red', 'font-size': '12px'});
                    if (phone.length == 11) {
                        //发送ajax
                        $.get('{{ url_for('user.send_message') }}', {phone: phone}, function (data) {
                            if (data.code == 200) {
                                alert('短信发送成功请查收！');
                            } else {
                                alert(data.msg);
                            }
                        });
                    } else {
                        span_obj.text('必须输入11位手机号码')
                    }
                });
            }
        )

    </script>
{% endblock %}